server:
  port: 8081

spring:
  application:
    name: SPRING-SECURITY-CLIENT
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dbs
    username: root
    password: 19052001SMKsSMKs@
    driver-class-name: com.mysql.jdbc.Driver
